# Generated by Django 3.1.7 on 2021-04-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobscrapper', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['title'], 'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
