# Generated by Django 3.1.7 on 2021-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscrapper', '0007_errors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='errors',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
