# Generated by Django 3.1.7 on 2021-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscrapper', '0008_auto_20210511_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
