# Generated by Django 3.1.7 on 2021-03-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210331_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='avatar',
        ),
    ]
