# Generated by Django 3.1.7 on 2021-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210430_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
