# Generated by Django 3.1.7 on 2021-05-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_profile_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url_for_hh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
