# Generated by Django 3.1.7 on 2021-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_profile_url_for_hh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='Получать рассылку'),
        ),
    ]
